---
title: "Research Opportunities in Latin America"
runtime: shiny
output: flexdashboard::flex_dashboard
resource_files:
- data/topic_names.csv
---

```{r libraries, warning = FALSE, message = FALSE, include = TRUE, echo = FALSE, results = "hide"}
libraries <- c(
"circlize",
"cowplot",
"factoextra",
"forcats",
"ggplot2",
"ggsci",
"RColorBrewer",
"dplyr",
"import"
)

for (x in libraries){
   if (!require(x, character.only = TRUE)) {
        install.packages(x, dependencies = TRUE)
        library(x, character.only = TRUE)
    } else {
      library(x, character.only = TRUE)
    }
}

### functions ###
import::here(.from = "./R/network_analysis/lib_network_analysis.R", 
  get_network,
  VizSpots)
```


Network Analysis {data-orientation=columns}
=====================================

Sidebar {.sidebar}
-------------------------------------

```{r}
selectInput("type", "Type of themes", c("methods", "NSF_general", "NSF_specific", "spatial scale", "theme", "water budget"), selected = "theme", multiple = FALSE,
  selectize = TRUE, width = NULL, size = NULL)
```

```{r}
sliderInput("country.threshold", label = "Country Threshold", min = 0, max = 500, value = 30, step = 10)
```

```{r}
sliderInput("percentile.threshold", label = "Percentile Threshold", min = 0, max = 0.95, value = 0.90, step = .05)
```

```{r}
checkboxInput("blindspot", label = "Blindspot", value = FALSE)
```

```{r}
checkboxInput("scaled", label = "Scaled results", value = FALSE)
```

```{r}
checkboxInput("filter_method", label = "Filter methods themes", value = TRUE)
```

```{r}
mdef <- get_network(type = "theme", prob = TRUE, filter_method = TRUE, blindspot = FALSE, country.threshold = 0, percentile.threshold = 0)
selectInput("countries", "Countries", rownames(mdef), selected = NULL, multiple = TRUE,
  selectize = TRUE, width = NULL, size = NULL)
checkboxInput("country_filter", label = "Filter countries", value = FALSE)
selectInput("themes", "Themes", colnames(mdef), selected = NULL, multiple = TRUE,
  selectize = TRUE, width = NULL, size = NULL)
checkboxInput("theme_filter", label = "Filter themes", value = FALSE)
```

**If the diagram fails to draw for some type of themes, lower the percentile threshold.**

**The options "Select country" and "Country threshold" are mutually exclusive.**

**The options "Select theme" and "Percentile threshold" are mutually exclusive.**

Column
-------------------------------------

### Chord Diagrams for Country and Theme

```{r , warning = FALSE, message = FALSE, include = TRUE, echo = FALSE}
renderPlot({
  m <- get_network(type = input$type, prob = TRUE, filter_method = input$filter_method, blindspot = input$blindspot, country.threshold = input$country.threshold, percentile.threshold = input$percentile.threshold, 
    country_filter = input$country_filter, countries = input$countries,
    theme_filter = input$theme_filter, themes = input$themes)
  VizSpots(m, input$scaled, cluster_color = FALSE)
})   
```
