---
title: "Graph Visualization in R"
author:
- name: Hervé Guillon
  affiliation: University of California, Davis
output:
  html_document:
    toc: true
    toc_float: true
    code_folding: hide
---

# Libraries and Data Loading

```{r libraries}
library("DiagrammeR")
library("visNetwork")
library("dplyr")
```

```{r gephi_test}

g <- visNetwork(gephi = "topic_network_complete_current_visible.json") %>%
visEdges(smooth = list(enabled = TRUE, type = "curvedCW"), physics = FALSE) %>%
visNodes(physics = TRUE)
visConfigure(g, enable = TRUE)
```


<!-- 


```{r data_loading}
# libs 
library("igraph")

# loading citation network
citation_network <- readRDS("citingDf.Rds")
source_ids <- readRDS("source_ids.Rds")

# load paper id
in_corpus_file <- "in_corpus.Rds"
in_corpus <- readRDS(in_corpus_file)

EndNoteIdcorpus <- unname(sapply(in_corpus$pdfs, substr, start = 1, stop = 10))
titleDocs <- readLines("../../../data/latin_america/water-management/topic-model/data/info.dat")
EndNoteIdLDA <- unname(sapply(titleDocs, substr, start = 1, stop = 10))

in_corpus_LDA <- in_corpus[which(EndNoteIdcorpus %in% EndNoteIdLDA), ]
EndNoteIdcorpus_LDA <- EndNoteIdcorpus[which(EndNoteIdcorpus %in% EndNoteIdLDA)]
source_ids_LDA <- source_ids[which(EndNoteIdcorpus %in% EndNoteIdLDA)]

# loading consolidated results
missing <- which(! EndNoteIdLDA %in% EndNoteIdcorpus)
predCountryMembership <- readRDS("predCountryMembership.Rds")
colnames(predCountryMembership) <- gsub("prob.", "", colnames(predCountryMembership))
consolidated_results <- readRDS("consolidated_results.Rds")
consolidated_results$ID <- EndNoteIdLDA[-missing]
consolidated_results$source_ids <- source_ids_LDA

consolidated_network <- consolidated_results[which(consolidated_results$country != "Irrelevant"), ]
consolidated_network <- consolidated_network[which(consolidated_network$source_ids %in% citation_network$citing), ]

consolidated_predCountryMembership <- predCountryMembership[which(consolidated_results$country != "Irrelevant"), ]
consolidated_predCountryMembership <- consolidated_predCountryMembership[which(consolidated_network$source_ids %in% citation_network$citing), ]

relevant_network <- citation_network[citation_network$citing %in% consolidated_network$source_ids, ]
relevant_network <- relevant_network[relevant_network$cited %in% consolidated_network$source_ids, ]
relevant_network$citing_country <- consolidated_network$country[match(relevant_network$citing, consolidated_network$source_ids)]
relevant_network$cited_country <- consolidated_network$country[match(relevant_network$cited, consolidated_network$source_ids)]
relevant_network <- relevant_network[relevant_network$cited_country %in% relevant_network$citing_country, ]
relevant_network$citing_country <- as.factor(as.character(relevant_network$citing_country))
relevant_network$cited_country <- factor(as.character(relevant_network$cited_country), levels = levels(relevant_network$citing_country))

# weighted adjacency matrix with country as vertex and number of citations as weight
# g <- graph_from_data_frame(relevant_network[, 3:4])
g <- graph_from_data_frame(relevant_network[, 1:2])
adj <- as.matrix(get.adjacency(g))


consolidated_predCountryMembership$source_ids <- consolidated_network$source_ids
countryNetwork <- consolidated_predCountryMembership[which(consolidated_network$source_ids %in% colnames(adj)), ]
countryNetwork <- countryNetwork[match(colnames(adj), countryNetwork$source_ids), ]
countryNetwork$source_ids <- NULL

rownames(adj) <- colnames(adj) <- rownames(countryNetwork)
saveRDS(adj, "adjacencyMatrix.Rds")
network_results <- t(as.matrix(countryNetwork)) %*% as.matrix(adj) %*% as.matrix(countryNetwork)
```

# Citation Networks {.tabset}

## Country Citation Network

```{r vis2}
network_results2 <- apply(network_results, 1, function(row) row / sum(row))
g <- from_adj_matrix(network_results2,
	mode = "directed",
	weighted = TRUE,
	use_diag = TRUE) %>%
join_node_attrs(
	df = get_degree_in(.)
) %>% mutate_node_attrs(
	indegree = rowSums(network_results2) * indegree
) %>% rescale_node_attrs(
	node_attr_from = indegree,
	to_lower_bound = 0.1,
	to_upper_bound = 0.5,
	node_attr_to = value
) %>%
mutate_node_attrs(
	width = value,
	xlabel = label) %>%
set_node_attr_to_display(
    attr = NULL
) %>%
rescale_edge_attrs(
	edge_attr_from = weight,
	to_lower_bound = 0.1,
	to_upper_bound = 1.5,
	edge_attr_to = width
) %>% mutate_edge_attrs(
	penwidth = width) %>%
set_edge_attrs(
	edge_attr = arrowhead,
	values = "none") %>%
set_edge_attrs(
	edge_attr = color,
	values = "black")

render_graph(g, layout = 'fr',
	width = 900,
	height = 900)


render_graph(g, layout = 'fr',
	width = 900,
	height = 900,
	output = "visNetwork")

nodes <- get_node_df(g)
edges <- get_edge_df(g) %>% select(-"id")

visNetwork(nodes, edges, height = "900px", width = "900px") %>% 
visEdges(smooth = list(enabled = TRUE, type = "curvedCW"), physics = FALSE) %>%
# visPhysics(stabilization = FALSE, solver = "forceAtlas2Based") %>%
visIgraphLayout(layout = "layout_with_fr", smooth = TRUE, physics = FALSE)

```

<!-- 

## Citation Network

```{r creating_graph}
g <- from_adj_matrix(adj,
	mode = "directed",
	weighted = FALSE,
	use_diag = FALSE)
```


```{r vis}
visNetwork(nodes = get_node_df(g), edges = get_edge_df(g)) %>%
visIgraphLayout(layout = "layout_randomly", smooth = FALSE, physics = FALSE) %>%
visOptions(
	nodesIdSelection = list(enabled = TRUE, selected = sample(get_node_df(g)$id, 1)),
	highlightNearest = list(enabled = TRUE, degree = 1, hover = FALSE)
)
## visPhysics(stabilization = FALSE, solver = "forceAtlas2Based",  barnesHut = list(gravitationalConstant = -500)) %>%
```

## Country Probabilities as a bi-partite Network

```{r country_bipartite}
bipartiteNetwork <- countryNetwork %>% 
mutate(id = rownames(countryNetwork)) %>%
mutate(id = gsub("text", "", id) %>% as.numeric()) %>%
reshape2::melt(id.vars = "id")

maxID <- max(bipartiteNetwork$id)

nodes <- bipartiteNetwork %>% select(-"value") %>%
mutate(variable = as.factor(variable) %>% as.numeric(variable) + maxID) %>% 
reshape2::melt(measure.vars = colnames(.)) %>% 
select(-"variable") %>%
rename(id = value) %>%
mutate(group = ifelse(id > maxID, "country", "text")) %>%
distinct()

edges <- bipartiteNetwork %>% 
rename(from = id, to = variable, width = value) %>%
mutate(to = as.factor(to) %>% as.numeric(to) + maxID )

visNetwork(nodes = nodes, edges = edges) %>%
visIgraphLayout(layout = "layout_randomly", smooth = FALSE, physics = FALSE) %>%
visLegend()
```

 --> -->