---
title: "Citation network"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Citation network}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---


# Citation Network

The citation network was extracted from article metadata which stores identifiers for the cited articles and citing article (i.e. the article to which the metadata are attached to).
A total of 29,900 citations were found between 4,603 unique articles of the English corpus.
The resulting bibliographic network is defined by its $4,603\times4,603$-adjacency matrix $B$ and is filtered to remove edges between node external to the collected corpus.
The citation network between countries, $B_C$ is obtained by:

\[ B_C = C^T \times B \times C \]

where $C$ is a $4,603\times23$-matrix containing the output of the machine learning probabilistic predictions of the location of study between $23$ possible country of study.
In consequence, $B_C$ is a weighted directed adjacency matrix.
Similar reasoning leads to the citation network between specific research topics, method topics and water budget topics by changing the matrix $C$ in the previous equation for the LDA probabilistic predictions of topics.

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```
### libraries ###
library("mlr")
library("OpenML")
library("NLP")
library("tm")
library("data.table")
library("mldr")
library("dplyr")
library("igraph")

### utils ###
import::here(.from = "./R/utils/lib_webscrapping.R",
  get.EndNoteIdcorpus,
  get.EndNoteIdLDA,
  QA.EndNoteIdCorpusLDA,
  align.dataWithEndNoteIdLDA,
  align.dataWithEndNoteIdcorpus,
  order.data
)


import::here(.from = "./R/network_analysis/lib_network_analysis.R", 
  make.countryNetwork,
  make.topicNetwork
 )

# data loading
englishCorpus_file <- "F:/hguillon/research/exploitation/R/latin_america/data/english_corpus.Rds"
englishCorpus <- readRDS(englishCorpus_file)

in_corpus_file <- "in_corpus.Rds"
in_corpus <- readRDS(in_corpus_file)
source_ids <- readRDS("source_ids.Rds") # aligned with corpus

citation_network <- readRDS("citingDf.Rds")

# get document IDs
EndNoteIdcorpus <- get.EndNoteIdcorpus(in_corpus)
EndNoteIdLDA <- get.EndNoteIdLDA(englishCorpus)
QA.EndNoteIdCorpusLDA(EndNoteIdLDA, EndNoteIdcorpus)

# align databases 
in_corpus <- align.dataWithEndNoteIdcorpus(in_corpus, EndNoteIdcorpus, EndNoteIdLDA)
source_ids <- align.dataWithEndNoteIdcorpus(source_ids, EndNoteIdcorpus, EndNoteIdLDA)

englishCorpus <- align.dataWithEndNoteIdLDA(englishCorpus, EndNoteIdLDA, EndNoteIdcorpus)

EndNoteIdLDA <- align.dataWithEndNoteIdLDA(EndNoteIdLDA, EndNoteIdLDA, EndNoteIdcorpus)
EndNoteIdcorpus <- align.dataWithEndNoteIdcorpus(EndNoteIdcorpus, EndNoteIdcorpus, EndNoteIdLDA)

QA.EndNoteIdCorpusLDA(EndNoteIdLDA, EndNoteIdcorpus)

# order them according to LDA database
source_ids <- order.data(source_ids, EndNoteIdLDA, EndNoteIdcorpus)
in_corpus <- order.data(in_corpus, EndNoteIdLDA, EndNoteIdcorpus)

predCountryMembership <- readRDS("predCountryMembership.Rds")
colnames(predCountryMembership) <- gsub("prob.", "", colnames(predCountryMembership))

# make the networks
countryNetwork <- make.countryNetwork(source_ids, citation_network)

type_list <- c("methods", "NSF_general", "NSF_specific", "spatial scale", "theme", "water budget")
for (tt in type_list) make.topicNetwork(source_ids, citation_network, type = tt, percentile.threshold = 0.90)

```