---
title: "Making the query"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Making the query}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  fig.height = 7,
  fig.width = 7, 
  comment = "#>"
)
```

# Purpose

This vignette describes how we assembled the corpus of documents

# Criteria for selecting an online database

We based our choice of online databases on the following criteria:

- inclusion of latin america paper databases (e.g. SciELO)
- number of results in English but also in Spanish and Portuguese
- alleged noise level from expert assessment of the relevancy of the results

# General work-flow

## Retrieve the references with online queries

1. perform the query on Web of Science or Scopus
2. if needed, select years to restrict the results to under 20k entries
3. save entries as `.csv` :
	+ for Scopus : 
		- on `Linux`, use `Chromium`, the export does not work with `Firefox`
		- wait for an email with the link for downloading, this might takes 10 minutes
4. once all entries are saved, [merge the `.csv` files](query_processing.html)
5. import the `.csv` to `Publish or Perish`
6. save the `.csv` into a `.ris`
7. import the `.ris` into `EndNote`
8. check for duplicate with EndNote


Note : you might need to fix the format between UTF-8 and ISO-8859-1 depending on the system you are running the scripts on.

## Webscrapping with EndNote

EndNote is unable to search for more than 1000 `.pdf` at once.

1. Create a Smart Group with the files without `.pdf`
2. Select all the bibliography with `ctrl + A`
3. Right click $\to$ `Find Full Text` 
4. `EndNote` starts searching for Full text
5. After $\sim 6$ hours, the process should terminate
6. Click on the Smart Groups `Found URL` and `Not Found` and move the references that `EndNote` was unable to find a `.pdf`for to the trash
7. Go back to step 2.


# Query results 

<center>


| Target corpus | Database                 | Search terms | Language filter | Number of results |
|:--------------|:-------------------------|:-------------|:----------------|:-----------------:|
| English       | Scopus                   | English      | English         |      14 486       |
|               | Web of Science – Core    | English      | English         |       4 214       |
|               | Web of Science – Biosis  | English      | English         |        194        |
|               | Web of Science – SciELO  | English      | English         |        25         |
|               | Web of Science – alleged | English      | English         |      15 524       |
| Spanish       | Scopus                   | English      | Spanish         |       1 017       |
|               | Web of Science – Core    | English      | Spanish         |        335        |
|               | Web of Science – Biosis  | English      | Spanish         |        10         |
|               | Web of Science – SciELO  | English      | Spanish         |        136        |
|               | Web of Science – Biosis  | Spanish      | Spanish         |         1         |
|               | Web of Science – SciELO  | Spanish      | Spanish         |        120        |
| Portuguese    | Scopus                   | English      | Portuguese      |        600        |
|               | Web of Science – Core    | English      | Portuguese      |        N/A        |
|               | Web of Science – Biosis  | English      | Portuguese      |         4         |
|               | Web of Science – SciELO  | English      | Portuguese      |        163        |
|               | Web of Science – Biosis  | Portuguese   | Portuguese      |        N/A        |
|               | Web of Science – SciELO  | Portuguese   | Portuguese      |        68         |


| Target corpus | Initial corpus size |
|:--------------|:-------------------:|
| English       |       34 443        |
| Spanish       |        1 619        |
| Portuguese    |         835         |

</center>


# Detailed queries

## Web of Science

### Query with English terms

```
SU = Water Resources AND (TS =((Water) AND ((Access) OR (Agricultural) OR (Aquifer*) OR (bay*) OR (catchment*) OR ("Change of storage") OR ("Climate change") OR (Contamination*) OR ("Cost-benefit analysis") OR ("Crop Coefficient?") OR (Dam*) OR ("Decision?maker?") OR (delta*) OR (Demand*) OR (Desalination*) OR (Drought*) OR ("Ecosystem service?") OR (Environment*) OR ("Environmental degradation?") OR (Environmental AND issue*) OR (Environmental AND justice) OR (estuar*) OR (Evapotranspiration*) OR (Flood*) OR ("Focus group?") OR (Fog*) OR (GIS) OR (Groundwater) OR (Hydroeconomic*) OR (Hydrologic) OR ("hydrologic region?") OR ("In-situ monitoring") OR (Interview*) OR (Irrigation) OR ("irrigation district?") OR (lake*) OR (Modeling) OR (Municipal) OR ("Non-point source?") OR (Optimization) OR (Over-draft*) OR ("Point source?") OR (Pollution*) OR (Precipitation*) OR (Protected) OR (Rain-fed) OR (Recharge*) OR (Recreation*) OR (Reliability) OR ("Remote sensing") OR (Reservoir*) OR (Resilience) OR (river*) OR (River*) OR (Rural) OR (Scenari*) OR ("Sea water intrusion?") OR ("Seawater intrusion?") OR (Sewage*) OR (Shortage*) OR (Simulation*) OR (Snowmelt) OR (Social AND justice) OR ("Social issue?") OR ("Political issue?") OR (Stakeholder*) OR (stream*) OR (Sub-basin*) OR (Subsidence) OR (Supply) OR (Surface AND water) OR (Surveying) OR ("Sustainability ind?") OR (Transboundar*) OR (Unprotected) OR (Urban) OR (Vulnerabilit*) OR (Wastewater) OR (Water) OR (footprint) OR (governance*) OR (market*) OR (over-allocation*) OR (price*) OR (treatment*) OR (watershed*) OR (Well*) OR (Wetland*)) AND ((puerto AND rico) OR (belize) OR (turks AND caicos AND islands) OR (aruba) OR (argentina) OR (jamaica) OR (virgin AND islands) OR (dominican AND republic) OR (haiti) OR (colombia) OR (grenada) OR (antigua AND barbuda) OR (saint AND vincent AND grenadines) OR (chile) OR (saint AND lucia) OR (bahamas) OR (saint AND kitts AND nevis) OR (guadeloupe) OR ("french guiana") OR (peru) OR (mexico NOT ("new mexico")) OR (suriname) OR (honduras) OR (panama) OR (brazil) OR (martinique) OR (cuba) OR (costa AND rica) OR (ecuador) OR (nicaragua) OR (saint AND barthelemy) OR (guatemala) OR (uruguay) OR (trinidad AND tobago) OR (venezuela) OR (bolivia) OR (cayman AND islands) OR (paraguay) OR (barbados) OR ("latin america?") OR ("south america?") OR (caribbean) OR ("central america?") OR (el AND salvador))))
```
### Query with Spanish terms

```
SU = Water Resources AND (TS =((Agua) AND ((Acceso) OR (Agrícola) OR (Acuífero?) OR (bahía?) OR (captación*) OR ("cambio de almacenamiento") OR ("Cambio climático") OR (Contaminación*) OR ("análisis de costo-beneficio") OR ("Coeficiente? de cultivo") OR (Presa?) OR ("tomadores de decisiones") OR (delta?) OR (Demanda) OR (Desalinización) OR (Sequía?) OR ("Servicio? del ecosistema") OR (Medioambiental) OR ("Degradación ambiental") OR (Problema? AND ambientale?) OR (Justicia AND ambiental) OR (estuario?) OR (Evapotranspiración) OR (Inundación?) OR ("Grupo? de enfoque") OR (Niebla?) OR (SIG) OR ("Agua subterránea") OR (Economía del agua) OR (Hidrológico) OR ("región* hidrológica?") OR ("Monitoreo in-situ") OR (Entrevista?) OR (Irrigación) OR ("distrito? de riego") OR (lago?) OR (Modelación) OR (Municipal) OR ("Contaminación de fuentes no puntuales") OR (Optimización) OR (Sobreexplotación) OR ("Contaminación de fuente puntual") OR (Polución) OR (Precipitación*) OR (protegid*) OR ("agricultura de tempral") OR (Recarga*) OR (Recreación) OR (confiabilidad) OR (Teledetección) OR (Embalse?) OR (resilencia) OR (río?) OR (Rural) OR (Escenario?) OR ("Intrusión salina") OR ("Agua? Residuale?") OR (Escasez) OR (Simulación*) OR (deshielo) OR (Justicia AND social) OR (Problema? sociale?) OR (Problema? político?) OR ("Partes interesadas") OR (corriente?) OR (Subcuenca?) OR (Hundimiento) OR (Abastecimiento) OR ("Agua superficial") OR ("Levantamiento de terreno") OR ("índice? de sustentabilidad") OR (Transfronteriz*) OR (Desprotegid*) OR (Urbano) OR (vulnerabilidad) OR ("derretimiento de nieve") OR (Agua) OR (huella) OR (Gobernanza) OR (mercado?) OR (Sobre-asignación) OR (precio?) OR (Tratamiento) OR (cuenca?) OR (pozo?) OR (Humedal) NOT (Marin?) ) AND (("puerto rico") OR (belice) OR ("Islas Turcas Caicos") OR (aruba) OR (argentina) OR (jamaica) OR ("Islas Virgenes") OR ("República Dominicana") OR (Haití) OR (colombia) OR (Granada) OR (antigua AND barbuda) OR ("San Vicente y las Granadinas") OR (chile) OR ("Santa Lucía") OR (bahamas) OR ("saint kitts" AND nevis) OR (guadalupe) OR ("Guayana Francesa") OR (Perú) OR (méxico NOT ("nuevo Mexico")) OR (suriname) OR (honduras) OR (Panamá) OR (brasil) OR (Martinica) OR (cuba) OR ("costa rica") OR (ecuador) OR (nicaragua) OR ("santo Barthelemy") OR (guatemala) OR (uruguay) OR (trinidad AND tobago) OR (venezuela) OR (bolivia) OR ("Islas Caimán") OR (paraguay) OR (barbados) OR ("America latina") OR (Sudamerica) OR (caribe) OR (Centroamérica) OR (el AND salvador) ) ) )
```

### Query with Portuguese terms

```
SU = Water Resources AND (TS = ((água) AND ((Acesso) OR (agricultura) OR (agropecuária) OR (aquíferos) OR (baia) OR (microbacia) OR ("alteração da reserva") OR ("mudança da reserva") OR ("mudança climática") OR (contaminação) OR ("análise de custo-benefício") OR ("coeficiente da cultura") OR (barragens) OR ("tomadores-de-decisão") OR ("tomadores de decisão") OR (delta*) OR (demanda) OR (dessalinização) OR (seca) OR ("serviços ecossistêmicos") OR (ambiente) OR ("degradação ambiental") OR (problemas AND ambientais) OR (justiça ambiental) OR (estuário) OR (evapotranspiração) OR (inundação) OR ("grupos focais") OR (névoa) OR (GIS) OR (SIG) OR ("água subterrânea") OR (hidro-econômico) OR (hidrológico) OR ("região hidrográfica") OR ("monitoramento in-situ") OR (entrevista) OR (irrigação) OR ("distrito de irrigação") OR (lago) OR (modelagem) OR (Municipal) OR ("poluição difusa") OR (otimização) OR ("poluição pontual") OR (poluição) OR (precipitação) OR (protegido) OR (recarga) OR (recreação) OR (segurança) OR ("sensoriamento remoto") OR (reservatórios) OR (resiliência) OR (rio) OR (Rural) OR (cenários) OR ("intrusão salina") OR (esgoto) OR (redução) OR (simulação) OR (água AND degelo) OR (justiça AND social) OR ("problemas políticos") OR ("problemas sociais") OR (Stakeholder*) OR (interessados) OR (rio) OR (riacho) OR (corpo d'água) OR (sub-bacia) OR (subsidência) OR (oferta) OR (água AND superficial) OR (pesquisa) OR (levantamento de dados) OR ("índice de sustentabilidade") OR (transfronteiriço) OR (não-protegido OR desprotegido) OR (Urbano) OR (vulnerabilidade) OR (águas residuárias) OR (água) OR (pegada hídrica) OR (governança) OR (mercado?) OR (over-allocation*) OR (preço?) OR (tratamento) OR (bacia hidrográfica) OR ("poço subterrâneo") OR (Pântanos) NOT (marinho) ) AND (("porto rico") OR (belize) OR ("Ilhas Turks e Caicos") OR (aruba) OR (argentina) OR (jamaica) OR ("Ilhas Virgens") OR (República Dominicana) OR (haiti) OR (Colômbia) OR (granada) OR (Antígua AND barbuda) OR ("são vicente e granadinas") OR (chile) OR ("Santa Lúcia") OR (bahamas) OR ("São Cristóvão e Nevis") OR (Guadalupe) OR ("Guiana Francesa") OR (peru) OR (méxico NOT ("Novo México")) OR (suriname) OR (honduras) OR (panama) OR (brasil) OR (Martinica) OR (cuba) OR ("costa rica") OR (Equador) OR (Nicarágua) OR ("São Bartolomeu") OR (guatemala) OR (uruguai) OR (trinidad AND tobago) OR (venezuela) OR (Bolívia) OR ("Ilhas Cayman") OR (paraguai) OR (barbados) OR ("América latina") OR ("América do Sul") OR (caribe) OR ("América Central") OR (el AND salvador) ) ) )
```

## Scopus

- allow for exporting 20k citation at once in `.csv`
- Scopus includes part of SciELO journals and has more journal in languages that are not English

### Query with English terms


```
KEY(
(Water) 
)
AND 
KEY
(
(Access) OR (Agricultural) OR (Aquifer*) OR (bay*) OR (catchment*) OR ("Change of storage") OR ("Climate change") OR (Contamination*) OR ("Cost-benefit analysis") OR ("Crop Coefficient?") OR (Dam*) OR ("Decision?maker?") OR (delta*) OR (Demand*) OR (Desalination*) OR (Drought*) OR ("Ecosystem service?") OR (Environment*) OR ("Environmental degradation?") OR (Environmental AND issue*) OR (Environmental AND justice) OR (estuar*) OR (Evapotranspiration*) OR (Flood*) OR ("Focus group?") OR (Fog*) OR (GIS) OR (Groundwater) OR (Hydroeconomic*) OR (Hydrologic) OR ("hydrologic region?") OR ("In-situ monitoring") OR (Interview*) OR (Irrigation) OR ("irrigation district?") OR (lake*) OR (Modeling) OR (Municipal) OR ("Non-point source?") OR (Optimization) OR (Over-draft*) OR ("Point source?") OR (Pollution*) OR (Precipitation*) OR (Protected) OR (Rain-fed) OR (Recharge*) OR (Recreation*) OR (Reliability) OR ("Remote sensing") OR (Reservoir*) OR (Resilience) OR (river*) OR (River*) OR (Rural) OR (Scenari*) OR ("Sea water intrusion?") OR ("Seawater intrusion?") OR (Sewage*) OR (Shortage*) OR (Simulation*) OR (Snowmelt) OR (Social AND justice) OR ("Social issue?") OR ("Political issue?") OR (Stakeholder*) OR (stream*) OR (Sub-basin*) OR (Subsidence) OR (Supply) OR (Surface AND water) OR (Surveying) OR ("Sustainability ind?") OR (Transboundar*) OR (Unprotected) OR (Urban) OR (Vulnerabilit*) OR (Wastewater) OR (Water) OR (footprint) OR (governance*) OR (market*) OR (over-allocation*) OR (price*) OR (treatment*) OR (watershed*) OR (Well*) OR (Wetland*) AND NOT (Marine)
)
AND KEY
(
("puerto rico") OR (belize) OR (turks AND caicos AND islands) OR (aruba) OR (argentina) OR (jamaica) OR ("virgin islands") OR (dominican AND republic) OR (haiti) OR (colombia) OR (grenada) OR (antigua AND barbuda) OR ("saint vincent" AND grenadines) OR (chile) OR ("saint lucia") OR (bahamas) OR ("saint kitts" AND nevis) OR (guadeloupe) OR ("french guiana") OR (peru) OR (mexico AND NOT ("New Mexico")) OR (suriname) OR (honduras) OR (panama) OR (brazil) OR (martinique) OR (cuba) OR ("costa rica") OR (ecuador) OR (nicaragua) OR ("saint barthelemy") OR (guatemala) OR (uruguay) OR (trinidad AND tobago) OR (venezuela) OR (bolivia) OR ("cayman islands") OR (paraguay) OR (barbados) OR ("latin america?") OR ("south america?") OR (caribbean) OR ("central america?") OR (el AND salvador)
) 
AND  DOCTYPE ( ar )  AND  ( EXCLUDE ( PREFNAMEAUID ,  "Anon#1" )  OR  EXCLUDE ( PREFNAMEAUID ,  "Undefined#Undefined" ) )  AND  ( EXCLUDE ( SUBJAREA ,  "MEDI" )  OR  EXCLUDE ( SUBJAREA ,  "BIOC" )  OR  EXCLUDE ( SUBJAREA ,  "IMMU" )  OR  EXCLUDE ( SUBJAREA ,  "ARTS" )  OR  EXCLUDE ( SUBJAREA ,  "VETE" )  OR  EXCLUDE ( SUBJAREA ,  "PHAR" )  OR  EXCLUDE ( SUBJAREA ,  "NURS" )  OR  EXCLUDE ( SUBJAREA ,  "PSYC" )  OR  EXCLUDE ( SUBJAREA ,  "PHYS" )  OR  EXCLUDE ( SUBJAREA ,  "NEUR" )  OR  EXCLUDE ( SUBJAREA ,  "HEAL" )  OR  EXCLUDE ( SUBJAREA ,  "DENT" )  OR  EXCLUDE ( SUBJAREA ,  "MATH" )  OR  EXCLUDE ( SUBJAREA ,  "Undefined" ) )  AND  ( LIMIT-TO ( LANGUAGE ,  "English" ) )
```

### Query with Spanish terms

```
KEY(
(Agua) 
)
AND 
KEY
(
(Acceso) OR (Agrícola) OR (Acuífero?) OR (bahía?) OR (captación*) OR ("cambio de almacenamiento") OR ("Cambio climático") OR (Contaminación*) OR ("análisis de costo-beneficio") OR ("Coeficiente? de cultivo") OR (Presa?) OR ("tomadores de decisiones") OR (delta?) OR (Demanda) OR (Desalinización) OR (Sequía?) OR ("Servicio? del ecosistema") OR (Medioambiental) OR ("Degradación ambiental") OR (Problema? AND ambientale?) OR (Justicia AND ambiental) OR (estuario?) OR (Evapotranspiración) OR (Inundación?) OR ("Grupo? de enfoque") OR (Niebla?) OR (SIG) OR ("Agua subterránea") OR (Economía del agua) OR (Hidrológico) OR ("región* hidrológica?") OR ("Monitoreo in-situ") OR (Entrevista?) OR (Irrigación) OR ("distrito? de riego") OR (lago?) OR (Modelación) OR (Municipal) OR ("Contaminación de fuentes no puntuales") OR (Optimización) OR (Sobreexplotación) OR ("Contaminación de fuente puntual") OR (Polución) OR (Precipitación*) OR (protegid*) OR ("agricultura de tempral") OR (Recarga*) OR (Recreación) OR (confiabilidad) OR (Teledetección) OR (Embalse?) OR (resilencia) OR (río?) OR (Rural) OR (Escenario?) OR ("Intrusión salina") OR ("Agua? Residuale?") OR (Escasez) OR (Simulación*) OR (deshielo) OR (Justicia AND social) OR (Problema? sociale?) OR (Problema? político?) OR ("Partes interesadas") OR (corriente?) OR (Subcuenca?) OR (Hundimiento) OR (Abastecimiento) OR ("Agua superficial") OR ("Levantamiento de terreno") OR ("índice? de sustentabilidad") OR (Transfronteriz*) OR (Desprotegid*) OR (Urbano) OR (vulnerabilidad) OR ("derretimiento de nieve") OR (Agua) OR (huella) OR (Gobernanza) OR (mercado?) OR (Sobre-asignación) OR (precio?) OR (Tratamiento) OR (cuenca?) OR (pozo?) OR (Humedal) AND NOT (Marin?)
)
AND KEY
(
("puerto rico") OR (belice) OR ("Islas Turcas Caicos") OR (aruba) OR (argentina) OR (jamaica) OR ("Islas Virgenes") OR ("República Dominicana") OR (Haití) OR (colombia) OR (Granada) OR (antigua AND barbuda) OR ("San Vicente y las Granadinas") OR (chile) OR ("Santa Lucía") OR (bahamas) OR ("saint kitts" AND nevis) OR (guadalupe) OR ("Guayana Francesa") OR (Perú) OR (méxico AND NOT ("nuevo Mexico")) OR (suriname) OR (honduras) OR (Panamá) OR (brasil) OR (Martinica) OR (cuba) OR ("costa rica") OR (ecuador) OR (nicaragua) OR ("santo Barthelemy") OR (guatemala) OR (uruguay) OR (trinidad AND tobago) OR (venezuela) OR (bolivia) OR ("Islas Caimán") OR (paraguay) OR (barbados) OR ("America latina") OR (Sudamerica) OR (caribe) OR (Centroamérica) OR (el AND salvador)
) 
AND  DOCTYPE ( ar )  AND  ( EXCLUDE ( PREFNAMEAUID ,  "Anon#1" )  OR  EXCLUDE ( PREFNAMEAUID ,  "Undefined#Undefined" ) )  AND  ( EXCLUDE ( SUBJAREA ,  "MEDI" )  OR  EXCLUDE ( SUBJAREA ,  "BIOC" )  OR  EXCLUDE ( SUBJAREA ,  "IMMU" )  OR  EXCLUDE ( SUBJAREA ,  "ARTS" )  OR  EXCLUDE ( SUBJAREA ,  "VETE" )  OR  EXCLUDE ( SUBJAREA ,  "PHAR" )  OR  EXCLUDE ( SUBJAREA ,  "NURS" )  OR  EXCLUDE ( SUBJAREA ,  "PSYC" )  OR  EXCLUDE ( SUBJAREA ,  "PHYS" )  OR  EXCLUDE ( SUBJAREA ,  "NEUR" )  OR  EXCLUDE ( SUBJAREA ,  "HEAL" )  OR  EXCLUDE ( SUBJAREA ,  "DENT" )  OR  EXCLUDE ( SUBJAREA ,  "MATH" )  OR  EXCLUDE ( SUBJAREA ,  "Undefined" ) )  AND  ( LIMIT-TO ( LANGUAGE ,  "Spanish" ) )
```

### Query with Portuguese terms

```
KEY(
(água) 
)
AND 
KEY
(
(Acesso) OR (agricultura) OR (agropecuária) OR (aquíferos) OR (baia) OR (microbacia) OR ("alteração da reserva") OR ("mudança da reserva") OR ("mudança climática") OR (contaminação) OR ("análise de custo-benefício") OR ("coeficiente da cultura") OR (barragens) OR ("tomadores-de-decisão") OR ("tomadores de decisão") OR (delta*) OR (demanda) OR (dessalinização) OR (seca) OR ("serviços ecossistêmicos") OR (ambiente) OR ("degradação ambiental") OR (problemas AND ambientais) OR (justiça ambiental) OR (estuário) OR (evapotranspiração) OR (inundação) OR ("grupos focais") OR (névoa) OR (GIS) OR (SIG) OR ("água subterrânea") OR (hidro-econômico) OR (hidrológico) OR ("região hidrográfica") OR ("monitoramento in-situ") OR (entrevista) OR (irrigação) OR ("distrito de irrigação") OR (lago) OR (modelagem) OR (Municipal) OR ("poluição difusa") OR (otimização) OR ("poluição pontual") OR (poluição) OR (precipitação) OR (protegido) OR (recarga) OR (recreação) OR (segurança) OR ("sensoriamento remoto") OR (reservatórios) OR (resiliência) OR (rio) OR (Rural) OR (cenários) OR ("intrusão salina") OR (esgoto) OR (redução) OR (simulação) OR (água AND degelo) OR (justiça AND social) OR ("problemas políticos") OR ("problemas sociais") OR (Stakeholder*) OR (interessados) OR (rio) OR (riacho) OR (corpo d'água) OR (sub-bacia) OR (subsidência) OR (oferta) OR (água AND superficial) OR (pesquisa) OR (levantamento de dados) OR ("índice de sustentabilidade") OR (transfronteiriço) OR (não-protegido OR desprotegido) OR (Urbano) OR (vulnerabilidade) OR (águas residuárias) OR (água) OR (pegada hídrica) OR (governança) OR (mercado?) OR (over-allocation*) OR (preço?) OR (tratamento) OR (bacia hidrográfica) OR ("poço subterrâneo") OR (Pântanos) AND NOT (marinho)
)
AND KEY
(
("porto rico") OR (belize) OR ("Ilhas Turks e Caicos") OR (aruba) OR (argentina) OR (jamaica) OR ("Ilhas Virgens") OR (República Dominicana) OR (haiti) OR (Colômbia) OR (granada) OR (Antígua AND barbuda) OR ("são vicente e granadinas") OR (chile) OR ("Santa Lúcia") OR (bahamas) OR ("São Cristóvão e Nevis") OR (Guadalupe) OR ("Guiana Francesa") OR (peru) OR (méxico AND NOT ("Novo México")) OR (suriname) OR (honduras) OR (panama) OR (brasil) OR (Martinica) OR (cuba) OR ("costa rica") OR (Equador) OR (Nicarágua) OR ("São Bartolomeu") OR (guatemala) OR (uruguai) OR (trinidad AND tobago) OR (venezuela) OR (Bolívia) OR ("Ilhas Cayman") OR (paraguai) OR (barbados) OR ("América latina") OR ("América do Sul") OR (caribe) OR ("América Central") OR (el AND salvador)
) 
AND  DOCTYPE ( ar )  AND  ( EXCLUDE ( PREFNAMEAUID ,  "Anon#1" )  OR  EXCLUDE ( PREFNAMEAUID ,  "Undefined#Undefined" ) )  AND  ( EXCLUDE ( SUBJAREA ,  "MEDI" )  OR  EXCLUDE ( SUBJAREA ,  "BIOC" )  OR  EXCLUDE ( SUBJAREA ,  "IMMU" )  OR  EXCLUDE ( SUBJAREA ,  "ARTS" )  OR  EXCLUDE ( SUBJAREA ,  "VETE" )  OR  EXCLUDE ( SUBJAREA ,  "PHAR" )  OR  EXCLUDE ( SUBJAREA ,  "NURS" )  OR  EXCLUDE ( SUBJAREA ,  "PSYC" )  OR  EXCLUDE ( SUBJAREA ,  "PHYS" )  OR  EXCLUDE ( SUBJAREA ,  "NEUR" )  OR  EXCLUDE ( SUBJAREA ,  "HEAL" )  OR  EXCLUDE ( SUBJAREA ,  "DENT" )  OR  EXCLUDE ( SUBJAREA ,  "MATH" )  OR  EXCLUDE ( SUBJAREA ,  "Undefined" ) )  AND  ( LIMIT-TO ( LANGUAGE ,  "Portuguese" ) )
```
