---
title: "Network visualization"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Network visualization}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

# Purpose

This vignette derives the node sizes and matrices required for re-creating network visualization using Gephi.

# Libraries

```{r}
library(wateReview)
```

# Data loading

```{r}
theme_adjacency_matrix <- readRDS(system.file("extdata", "rawTopicNetwork_theme.Rds", package = "wateReview"))
NSF_general_adjacency_matrix <- readRDS(system.file("extdata", "rawTopicNetwork_NSF_general.Rds", package = "wateReview"))
NSF_specific_adjacency_matrix <- readRDS(system.file("extdata", "rawTopicNetwork_NSF_specific.Rds", package = "wateReview"))
country_adjacency_matrix <- readRDS(system.file("extdata", "countryNetwork.Rds", package = "wateReview"))
```

# Normalizing 

We normalize all the adjacency matrices with `normalize_adj_matrix()`.

```{r}
normalized_theme_adjacency_matrix <- normalize_adj_matrix(theme_adjacency_matrix)
normalized_NSF_general_adjacency_matrix <- normalize_adj_matrix(NSF_general_adjacency_matrix)
normalized_NSF_specific_adjacency_matrix <- normalize_adj_matrix(NSF_specific_adjacency_matrix)
normalized_country_adjacency_matrix <- normalize_adj_matrix(country_adjacency_matrix)
head(normalized_country_adjacency_matrix)
```

# Node sizes

We now derive the node size with `colSums`.

```{r}
theme_node_size <- colSums(normalized_theme_adjacency_matrix)
NSF_general_node_size <- colSums(normalized_NSF_general_adjacency_matrix)
NSF_specific_node_size <- colSums(normalized_NSF_specific_adjacency_matrix)
country_node_size <- colSums(normalized_country_adjacency_matrix)
head(country_node_size)
```