## Intro
The famous Blue Marble photograph taken by the crew of Apollo 17 embodies the abundance of water that supported the emergence of life on Earth and is intrinsically linked to human health, ecosystem function, and economic prosperity. 
Yet, this iconic picture belies the pressures facing freshwater resources today, brought about by anthropogenic threats of human population growth and urbanization, climate variability and change, economic growth and consumption patterns, and the spread of misinformation and mistrust in science [@IPCC2014]. 
To support society’s water needs in this context, decision-making must be based on evidence from robust water resources research in a diversity of scientific fields, which spans spatial and temporal scales of resource management, and is connected by collaborations within and across countries and disciplines [@Astudillo2016].
This definition of robust research can be used to identify bright and blind spots of past scientific inquiry, that is topics and locations where water issues are more- or less-thoroughly understood, respectively [@Cvitanovic2018].

Latin America embodies these water challenges as a region with unequal distribution of abundant water resources, mounting pollution and the highest income inequality in the world [@Varis2019].
Marked disparities between countries affect water resources management, such as water supply, climate change vulnerability, urbanization level, culture, and scientific productivity [@Ciocca2017; @citeforeach].
Countries with abundant surface water resources, such as Brazil, experience water-scarcity due to a disconnection between the locations of available water and population centers [@Formiga2005], while others face flooding and melting glaciers, such as Argentina and Bolivia [@cite].
Latin America is among the most urbanized regions in the world and these high density areas face particular vulnerability to water quality and supply risks [@WorldBank].
The city of Sāo Paulo almost ran out of water during a drought in 2014, while Mexico City is steadily and rapidly depleting their groundwater supply [@cite].
Pressures on water resources from urban populations are compounded by poor farming practices, unregulated industry, and aging infrastructure across the region.
These water challenges are expected to intensify due to climate change as variations in precipitation, temperature, and evaporation threaten water availability for current and future water users around the globe, and particularly in Latin America [@Dussaillant2019; @Garreaud2017; @Zaninelli2019].
Uncertainty surrounds the reliability of water supplies to meet future needs and availability of funds for scientific research to address future water scarcity [@Andrade2019; @Lazcano201].

