# Introduction

The famous Blue Marble photograph taken by the crew of Apollo 17 embodies the abundance of water that supported the emergence of life on Earth and is intrinsically linked to human health, ecosystem function, and economic prosperity. 
Yet, this iconic picture belies the pressures facing freshwater resources today, brought about by anthropogenic threats of human population growth and urbanization [@Jenerette2006; @Immerzeel2019], climate variability and change [@Gosling2016], economic growth and consumption patterns [@Mcdonald2014; @Odorico2018], and the spread of misinformation and mistrust in science [@IPCC2014]. 
To support societal and ecological water needs in this context, decision-making must be based on evidence from robust water resources research in a diversity of scientific fields [@Uzzi2013], which spans spatial [@Zipper2020] and temporal scales of resource management, and is connected by collaborations within and across countries and disciplines [@Astudillo2016].
This definition of robust research can be used to identify bright and blind spots of past scientific inquiry, that is topics and locations where water issues are more- or less-thoroughly understood, respectively [@Cvitanovic2018].

Latin America embodies these water challenges with its unequal distribution of abundant water resources for a small population [@desa2019united], mounting pollution and the highest income inequality in the world [@Varis2019].
Marked disparities between and within countries affect water resources management, such as water supply, climate change vulnerability, urbanization level, habits and scientific productivity [@Ciocca2017; @Lyon2019].
Countries with abundant surface water resources, such as Brazil, experience water scarcity due to a mismatch between water-rich areas and population centers [@Formiga2005], while others face flooding and melting glaciers, such as Argentina, Chile and Bolivia [@Barros2015; @Soruco2015; @Masiokas2019].
Latin America is among the most urbanized regions in the world and these high density areas face particular vulnerability to water quality and supply risks [@Kim2019].
The city of Sāo Paulo nearly ran out of water during a 2014 drought, while Mexico City is steadily and rapidly depleting its groundwater supply [@Aguilar2015].
Urban pressures on water resources are compounded by poor farming practices, unregulated industries, and aging infrastructure across the region.
These water challenges are expected to intensify due to climate change as variations in precipitation, temperature, and evaporation threaten water availability for current and future water users around the globe, and particularly in Latin America [@Dussaillant2019; @Garreaud2017; @Gesualdo2019; @Zaninelli2019].
Uncertainty surrounds the reliability of water supplies to meet future needs as well as the availability of funds for scientific research to address future water scarcity [@Andrade2019].
There is a need for comparative research within Latin America, rather than comparisons within and between the United States and Europe where scientific and monetary resources have been comparatively more plentiful.
