# Results & Discussion

## Time line

The scientific production of water research based in Latin America and the Caribbean has grown exponentially over the last four decades, revealing a significant increase in the contribution of knowledge that this region is providing to the global scientific community.
We grouped research by socio-hydrologic cluster to identify how countries with similar social and hydrological systems contributed to water research over time (Figure 1).
The growth in research is not distributed equally across the region and is dominated by contributions from the two largest countries in Latin America, Brazil and Mexico.
A residual analysis of the exponential growth of annual research by country cluster identifies trends in annual scientific output.
Since 2000, the first year when we have over 30 research papers in each language, there were three distinct periods of water research.
Annual output was lower than the general trend for the first several years of the 21st century, followed by a period of relatively higher output and ends with a trend of decreasing growth.
There may be a connection between the trend in regional output and Brazil's economic crisis in 2012....


## Chord diagram

Inequalities in locations and themes of research are revealed in a chord diagram that describes the composition of water research in Latin America and the Caribbean (Figure 2).
The chord widths indicate the proportion of a specific research theme within the top 25% of research for a given country.
While Brazil, Mexico, Argentina and Chile dominate the research landscape, countries in the Caribbean and most of Central America are excluded from the analysis due to their statistically insufficient number of articles (less than 30), indicating a relative shortage of research in these regions.
A country's socio-hydrologic cluster correlates to its contribution to overall research output, suggesting that a country's resources, geography and history influence the scientific activity of researchers working there.
Similarly, water research is not distributed equally among disciplines and there is a relative shortage of research in the social sciences.
While Mexico contributes most to the social science research, it is a small proportion of its overall output.
Water research is conducted primarily in the physical and life sciences, with Mexico and Argentina alternating for second highest output after Brazil, respectively.

## Network analysis

Given the high volume of research from Brazil highlighted above, one may wonder if this large quantity of scientific output is also proportionally more influential than other countries.
To assess the importance of Brazil within the community of water resources researchers in Latin America and the Caribbean, we mapped the citation network of our corpus (Figure 5).
The network shows the net-connectivity between countries and describes a community where Brazil is the centerpiece and the geographic location or socio-hydrologic system of a country do not indicate extent of collaboration.


## Maps

Hexagonal map stuff here...



## Normality

After assessing trends in the corpus, we further analyzed results from the topic model and text mining to identify bright spots and blind spots of specific topics water research in Latin America and the Caribbean.
We define successful research as having a distribution that is close to the standard normal distribution and with high entropy.
When applied to our corpus, these concepts highlight areas within water resources research that are relatively under-studied.

Water research in Latin America and the Caribbean has generally higher normality across countries than documents (Figure 3).
A review of the normalities of the components of the water budget validates this analysis approach.
Rivers and precipitation, which must be monitored and understood to manage water resources, have distributions closest to normal, while glaciers are far from normal distribution because few countries have glaciers to study.
Assuming that high normality indicates success, statistics, quantitative methods and water sampling are identified as bright spots of water research methods.
Niche topics, such as irrigation and isotopes, have high normality across countries but low normality across documents and lie somewhere between bright and blind spots.
Such research topics are either infrequently mentioned or, if mentioned, are the main subject of a paper and lack integration in interdisciplinary research.
The least normality is seen in two topics of great importance for water management: reservoirs and risk assessment.



## LDA performance
The aforementioned findings are based on the output of a topic model of the articles written in English, predicated on the assumption that the English language corpus accurately represents the breadth of research done throughout the region and published in English, Spanish and Portuguese.
This assumption is supported by comparing the topic model performance of the three corpus (Figure 6).
One third of the NSF specific categories present in the English corpus are present in all languages.
Importantly, most of the top 10% (?) of research is captured in this subset of categories (9 of 13).
Another third of the categories are present in two languages and the last third is only present in English.
