---
title: "Classifying Documents Metadata"
author: Hervé Guillon
date: July 18, 2019
output:
  html_document:
    toc: true
    toc_float: true
    code_folding: hide
---

## Summary

## Rationale

The human reading collected metadata about: the document location, the document funding source and the document spatial and temporal scales.
I focus here on the identifying scales.

## Problem Definition

The problem at hand is a classification task.
This classification is characterized by having multiple labels.
In other words, one document can have the spatial scales labels: "Day" and "Week" and "Year" at the same time.
This problem of classification is different of the simpler problem of having to predict one label with different values: a multi-class classification problem.
For example, the current problem could be conceptualized as one label "Timescale" taking the values "Day", "Week", "Year" and so on.

Two main approaches exist to solve such a multilabel classification problem.
The first one is to use algorithm adapted for such a task.
The second one is to transform the problem to make it tractable.
Such a transformation can be achieved through two schemes: Binary Relevance (BR) and Label Powerset.
In the LP approach, the multilabel problem is transformed into a multi-class classification of the labelsets.
In the BR approach, the problem is decomposed in a set of binary problems.
In addition, we test more refined BR approaches: classifier chains were the binary classifiers are trained in a given order to predict the labels; nested stacking were the labels are approximated successively by learners and dependent binary relevance where every other labels are used as the input for each label-specific binary learners and stacking which combine dependent binary relevance and nested stacking.

The performance metric used is the multilabel Hamming loss corresponding to the proportion of incorrectly predicted labels.
We also profide the subset 0 1 metric corresponding to the proportion of observations for which the complete set of label is correctly predicted.

## Temporal Scales

Identifying temporal scales give avenues to 



### Technical consideration

## Spatial Scales

---

Hervé Guillon

---